ORDER_CREATED = "order.created"
ORDER_STATUS_CHANGED = "order.status_changed"
ORDER_SHIPPED = "order.shipped"
PRODUCT_UPDATED = "product.updated"
PROMO_USED = "promo.used"
REVIEW_CREATED = "review.created"

ORDER_CREATED_CUSTOMER = "order.created.customer"
ORDER_STATUS_CHANGED_CUSTOMER = "order.status_changed.customer"
ORDER_PROCESSING_CUSTOMER = "order.processing.customer"
ORDER_SHIPPED_CUSTOMER = "order.shipped.customer"
ORDER_DELIVERED_CUSTOMER = "order.delivered.customer"
ORDER_CANCELLED_CUSTOMER = "order.cancelled.customer"
